lexicon = [
  {
    "sentiment":
    {
      "positive": {
        'ability':1,
        'able':1,
        'achieve':1,
        'action':1,
        'advance':1,
        'aimed':1,
        'allowing':1,
        'amazing':1,
        'attainment':1,
        'being':1,
        'belief':1,
        'believe':1,
        'best':1,
        'better':1,
        'blessings':1,
        'blooming':1,
        'brothers':1,
        'can':1,
        'cares':1,
        'celebrate':1,
        'confidence':1,
        'confident':1,
        'considerable':1,
        'continue':1,
        'continuous':1,
        'create':1,
        'creation':1,
        'credit':1,
        'defending':1,
        'definite':1,
        'democracy':1,
        'development':1,
        'discover':1,
        'discovers':1,
        'disneyland':1,
        'dispositions':1,
        'eager':1,
        'earned':1,
        'easier':1,
        'easily':1,
        'embrace':1,
        'encouraging':1,
        'express':1,
        'fact':1,
        'finish':1,
        'friendship':1,
        'first':1,
        'funny':1,
        'gain':1,
        'generous':1,
        'get':1,
        'give':1,
        'goal':1,
        'god':1,
        'good':1,
        'gotten':1,
        'great':1,
        'greatest':1,
        'greatly':1,
        'grow':1,
        'happiness':1,
        'happy':1,
        'help':1,
        'highly':1,
        'honored':1,
        'hopeful':1,
        'ideas':1,
        'imagination':1,
        'imagine':1,
        'impress':1,
        'inspiring':1,
        'intelligence':1,
        'interest':1,
        'interesting':1,
        'its':1,
        'journey':1,
        'lead':1,
        'likely':1,
        'livelihoods':1,
        'lives':1,
        'live':1,
        'lucky':1,
        'made':1,
        'make':1,
        'making':1,
        'many':1,
        'might':1,
        'mind':1,
        'miracles':1,
        'more':1,
        'most':1,
        'motivate':1,
        'much':1,
        'music':1,
        'natasha':1,
        'new':1,
        'opportunity':1,
        'own':1,
        'parties':1,
        'passions':1,
        'permit':1,
        'persistent':1,
        'personal':1,
        'positive':1,
        'positivity':1,
        'rekindle':1,
        'relations':1,
        'reputation':1,
        'respect':1,
        'rewarded':1,
        'romanoff':1,
        'satisfied':1,
        'selfdiscipline':1,
        'selfknowlege':1,
        'spiritual':1,
        'succeed':1,
        'teachings':1,
        'truth':1,
        'validates':1,
        'wealth':1,
        'wish':1,
        'worth':1
        },
      "negative": {
        'absurd':1,
        'against':1,
        'anger':1,
        'angry':1,
        'aprehend':1,
        'arduous':1,
        'arguments':1,
        'avengers':1,
        'battle':1,
        'behind':1,
        'blind':1,
        'bribe':1,
        'cautious':1,
        'challenge':1,
        'chance':1,
        'cocky':1,
        'conflict':1,
        'cruel':1,
        'cruelty':1,
        'dare':1,
        'debate':1,
        'defects':1,
        'demand':1,
        'depressed':1,
        'desire':1,
        'despite':1,
        'didnt':1,
        'different':1,
        'disappointment':1,
        'disemboweled':1,
        'disfigured':1,
        'dont':1,
        'doubtful':1,
        'drama':1,
        'drug':1,
        'emotional':1,
        'emotions':1,
        'encounter':1,
        'endeaver':1,
        'endure':1,
        'endured':1,
        'energy':1,
        'enjoyed':1,
        'enthusiasm':1,
        'evil':1,
        'extinguish':1,
        'extreme':1,
        'fear':1,
        'fearful':1,
        'fighting':1,
        'foolish':1,
        'government':1,
        'hard':1,
        'hostages':1,
        'hydra':1,
        'ignorance':1,
        'isnt':1,
        'judgmental':1,
        'least':1,
        'loki':1,
        'manipulate':1,
        'misdeeds':1,
        'mistakes':1,
        'morbid':1,
        'need':1,
        'negative':1,
        'negativity':1,
        'never':1,
        'no':1,
        'nonsense':1,
        'not':1,
        'nothing':1,
        'pander':1,
        'resistance':1,
        'ruin':1,
        'scared':1,
        'sickened':1,
        'sorry':1,
        'terrorists':1,
        'threatening':1,
        'tortured':1,
        'wasnt':1,
        'without':1
        },
      "neutral": 
        {
        'a':1,
        'about':1,
        'afterwards':1,
        'again':1,
        'age':1,
        'all':1,
        'already':1,
        'also':1,
        'american':1,
        'apache':1,
        'appear':1,
        'apple':1,
        'assembly':1,
        'assumptions':1,
        'attitude':1,
        'aura':1,
        'banner':1,
        'barton':1,
        'be':1,
        'because':1,
        'been':1,
        'before':1,
        'beforehand':1,
        'beginning':1,
        'bodies':1,
        'boot':1,
        'bottom':1,
        'buy':1,
        'case':1,
        'change':1,
        'civilization':1,
        'class':1,
        'clear':1,
        'entirely':1,
        'evidence':1,
        'exemption':1,
        'experiment':1,
        'find':1,
        'fire':1,
        'habit':1,
        'has':1,
        'have':1,
        'havent':1,
        'having':1,
        'ignored':1,
        'impact':1,
        'kept':1,
        'kindled':1,
        'knives':1,
        'know':1,
        'known':1,
        'laws':1,
        'main':1,
        'majority':1,
        'mankind':1,
        'men':1,
        'meanings':1,
        'meet':1,
        'mental':1,
        'military':1,
        'money':1,
        'must':1,
        'my':1,
        'myself':1,
        'now':1,
        'pass':1,
        'politics':1,
        'reputation':1,
        'trend':1,
        'unique':1,
        'want':1,
        'whole':1,
        'wielded':1,
        'worked':1,
        'working':1,
        'worth':1,
        'would':1,
        'year':1,
        'you':1,
        'your':1,
        'yourself':1
        }
    },
    "domain":
    {
      "financial": [],
      "behavioral": [],
      "scientific": [],
      "educational": [],
      "politics": [],
      "relationships": []
    },
    "behavior":
    {
      "aggressive": {
                      'absurd': 1,
                      'action': 1,
                      'advance': 1,
                      'against': 1,
                      'aimed': 1,
                      'anger': 1,
                      'angry': 1,
                      'arguments': 1,
                      'battle': 1,
                      'bribe': 1,
                      'challenge': 1,
                      'change': 1,
                      'cocky': 1,
                      'conflict': 1,
                      'cruel': 1,
                      'cruelty': 1,
                      'demand': 1,
                      'disemboweled': 1,
                      'dismembered': 1,
                      'evil': 1,
                      'extreme': 1,
                      'fighting': 1,
                      "fire": 1,
                      'make': 1,
                      'making': 1,
                      'manipulate': 1,
                      'military': 1,
                      'missiles': 1,
                      'oppression': 1,
                      'oppressive': 1,
                      'passions': 1,
                      'persistent': 1,
                      'politics': 1,
                      'raid': 1,
                      'resistance': 1,
                      'ruin': 1,
                      'scoundrels': 1,
                      'shake': 1,
                      'take': 1,
                      'terrorists': 1,
                      'threatening': 1,
                      'tortured': 1,
                      'war': 1,
                      'wielded': 1
      },
      "passive": {
                  'allowing': 1,
                  'appear': 1,
                  'assumptions': 1,
                  'blessings': 1,
                  'cautious': 1,
                  'chance': 1,
                  'congress': 1,
                  'depressed': 1,
                  'doubtful': 1,
                  'dreams': 1,
                  'enjoyed': 1,
                  'fear': 1,
                  'fearful': 1,
                  'hostages': 1,
                  'leave': 1,
                  'love': 1,
                  'lucky': 1,
                  'miracles': 1,
                  'pass': 1,
                  'please': 1,
                  'prone': 1,
                  'satisfied': 1,
                  'scared': 1,
                  'sensible': 1,
                  'service': 1,
                  'spiritual': 1,
                  'subconscious': 1,
                  'suspend': 1,
                  'thank': 1,
                  'under': 1,
                  'vexation': 1,
                  'whatever': 1
      },
      "mentoring": {
                    'ability': 1,
                    'achieve': 1
                    'allowing': 1,
                    'apprehend': 1,
                    'attainment': 1,
                    'cares': 1,
                    'class': 1,
                    'confidence': 1,
                    'confident': 1,
                    'create': 1,
                    'creates': 1,
                    'creation': 1,
                    'defending': 1,
                    'development': 1,
                    'embrace': 1,
                    'encouraging': 1,
                    'friendship': 1,
                    'generous': 1,
                    'good': 1,
                    'honored': 1,
                    'impress': 1,
                    'inspiring': 1,
                    'intelligence': 1,
                    'kindled': 1,
                    'know': 1,
                    'known': 1,
                    'lead': 1,
                    'led': 1,
                    'mind': 1,
                    'minds': 1,
                    'motivate': 1,
                    'offer': 1,
                    'opportunity': 1,
                    'plan': 1,
                    'relationships': 1,
                    'respect': 1,
                    'selfdiscipline': 1,
                    'selfknowledge': 1,
                    'sensible': 1,
                    'sharing': 1,
                    'sorry': 1,
                    'study': 1,
                    'task': 1,
                    'teachings': 1,
                    'think': 1
      },
      "inquisitive": {
                      'about': 1,
                      'arguments': 1,
                      'belief': 1,
                      'challenge': 1,
                      'class':1,
                      'create': 1,
                      'creates': 1,
                      'creation': 1,
                      'debates': 1,
                      'desire': 1,
                      'development': 1,
                      'discover': 1,
                      'discovers': 1,
                      'eager': 1,
                      'experiment': 1,
                      'experiments': 1,
                      'experimenting': 1,
                      'exploration': 1,
                      'find': 1,
                      'interest': 1,
                      'interesting': 1,
                      'journey': 1,
                      'mental': 1,
                      'need': 1,
                      'passions': 1,
                      'persistent': 1,
                      'read': 1,
                      'rekindle': 1,
                      'retrieves': 1,
                      'scientific': 1,
                      'study': 1,
                      'think': 1,
                      'thinking': 1,
                      'want': 1,
                      'wonder': 1
      },
      "transaction": {
                      'age': 1,
                      'blessings': 1,
                      'bribe': 1,
                      'buy': 1,
                      'change': 1,
                      'closes': 1,
                      'conclusion': 1,
                      'credit': 1,
                      'finish': 1,
                      'first': 1,
                      'fortune': 1,
                      'gain': 1,
                      'get': 1,
                      'give': 1,
                      'had': 1,
                      'have': 1,
                      'held': 1,
                      'hostages': 1,
                      'increase': 1,
                      'kept': 1,
                      'last': 1,
                      'lucky': 1,
                      'made': 1,
                      'make': 1,
                      'making': 1,
                      'million': 1,
                      'money': 1,
                      'net': 1,
                      'offer': 1,
                      'own': 1,
                      'politics': 1,
                      'possessed': 1,
                      'relationships': 1,
                      'return': 1,
                      'rewarded': 1,
                      'richest': 1,
                      'spend': 1,
                      'spends': 1,
                      'state': 1,
                      'two': 1,
                      'wealth': 1,
                      'worth': 1
      }
    }
  }
]
